services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - WATCHPACK_POLLING=true  # Fixes file watching in Docker
      - FAST_REFRESH=true
      - HOST=0.0.0.0
    networks:
      - app-network
    command: npm start

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - HOST=0.0.0.0
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge
