# Use Node.js as the base image
FROM node:16

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the application port
EXPOSE 3030

# Start the application
#CMD ["npx", "nodemon", "server.js"]git